worker_processes auto;

events {
    worker_connections 1024;
}

http {
    gzip on;
    gzip_types application/json;
    gzip_min_length 256;

    sendfile on;
    keepalive_timeout 65;

    log_format safe '$remote_addr - $remote_user [$time_local] '
                    '"$request_method $uri" $status $body_bytes_sent '
                    '"$http_user_agent"';

    # ✅ Set CORS Headers for Actual Requests
                map $http_origin $cors_allow_origin {
                    default "";
                    "http://localhost:5173" "$http_origin";
                    #"https://attendez.buildapp.in" "$http_origin";
                }

    access_log /var/log/nginx/access.log safe;

    # Rate limit: 5 requests/sec/IP
    limit_req_zone $binary_remote_addr zone=rate_limit_zone:10m rate=5r/s;

    server {
        listen 80;

        limit_req zone=rate_limit_zone burst=10 nodelay;

        # 🚫 Block Swagger
        location ~* ^/(swagger-ui|v3/api-docs)/ {
            return 403;
        }

        # 🚫 Block static asset leaks
        location ~* \.(html|css|js|png|jpe?g|gif|ico|svg|woff2?|ttf|eot)$ {
            return 403;
        }

        location / {
            # ✅ CORS Preflight Requests
            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' "$http_origin" always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                return 204;
            }

            # ✅ Proxy other requests to Spring Boot
            proxy_pass http://app:8080;
            proxy_http_version 1.1;
            proxy_read_timeout 60s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;



            add_header 'Access-Control-Allow-Origin' "$cors_allow_origin" always;

#              add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            limit_except GET POST DELETE OPTIONS {
                deny all;
            }
        }
    }
}
