services:
  redis:
    build:
      context: ./redis-setup
      dockerfile: Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: attendance-redis-v3
    expose:
      - "6379"
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

    # Huge performance stability improvement for Redis
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - backend

  app:
    image: saip2005/attendez-app:1.4
    container_name: attendance-app-v3
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - backend

  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance-fastapi-v1
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: attendance-nginx-v3
    ports:
      - "80:80"
    depends_on:
      - app
      - fastapi-app
    restart: always
    networks:
      - backend

  cloudflared:
    build:
      context: ./cloudflared
      dockerfile: Dockerfile
    container_name: attendance-cloudflared-v3
    depends_on:
      - nginx
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_KEY}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_KEY}
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus-attx
    user: root
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana-attx
    ports:
      - "3000:3000"
    restart: always
    user: root
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - backend

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter-attx
    restart: always
    environment:
      REDIS_ADDR: redis://attendance-redis-v3:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend



volumes:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  backend:
    driver: bridge
