services:
  redis:
    build: ./redis  # Points to folder with Dockerfile + redis.conf
    container_name: redis-secure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
