version: '3.8'

services:
  redis:
    image: redis:7.4.3-alpine
    container_name: redis-secure
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourStrongRedisPassword
    command: >
      redis-server
      --requirepass sZJ61IvZBa6G6609fEiiqV71MzvUTW
      --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
