services:
  redis:
    build:
      context: ./redis-setup
      dockerfile: Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: attendance-redis-v5
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks: [backend]

  mongodb:
    build:
      context: ./mongo-setup
      dockerfile: Dockerfile
    container_name: attendance-mongo-v5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--username", "${MONGO_USERNAME}", "--password", "${MONGO_PASSWORD}", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks: [backend]

  app:
    build:
      context: ./springBoot
      dockerfile: Dockerfile
    container_name: attendance-app-v5
    image: saip2005/attendez-app:1.3
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks: [backend]

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: attendance-nginx-v5
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      # Mount certs
      - ./certs/attendez.ssn.net.crt:/etc/ssl/certs/attendez.ssn.net.crt:ro
      - ./certs/attendez.ssn.net.key:/etc/ssl/private/attendez.ssn.net.key:ro
    networks: [ backend ]

  mongo-backup:
    image: mongo:8.0
    container_name: attendance-mongo-backup-v5
    volumes:
      - ./mongo_backups:/backups/mongo
    environment:
      TZ: Asia/Kolkata
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    entrypoint: >
      sh -c "
      apt-get update && apt-get install -y cron && \
      echo 'Starting immediate backup...' && \
      mongodump --uri=\"mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/AttendEz?authSource=admin\" --out=/backups/mongo/dump_$(date +%F_%H-%M-%S) --gzip && \
      find /backups/mongo -mindepth 1 -maxdepth 1 -type d -mtime +3 -exec rm -rf {} + && \
      echo '1 0 * * * root mongodump --uri=\"mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/AttendEz?authSource=admin\" --out=/backups/mongo/dump_`date +\\%F_\\%H-\\%M-\\%S` --gzip && find /backups/mongo -mindepth 1 -maxdepth 1 -type d -mtime +3 -exec rm -rf {} +' > /etc/cron.d/mongo-backup && \
      chmod 0644 /etc/cron.d/mongo-backup && \
      cron -f
      "



    networks:
      - backend
    depends_on:
      mongodb:
        condition: service_healthy




volumes:
  redis-data:
  mongo-data:
networks:
  backend:
