spring.application.name=Smart Attendance Project
server.port=8080
spring.devtools.restart.enabled=true
spring.data.mongodb.uri=${API_KEY}
server.address=0.0.0.0
server.error.include-stacktrace=never
server.error.include-message=never
# Optional tuning
spring.data.redis.timeout=5000ms
spring.data.redis.client-name=attendez
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
# Use lettuce explicitly if switching from Jedis
spring.data.redis.client-type=lettuce
# Expose only what Prometheus needs
management.endpoints.web.exposure.include=health,info,prometheus

# Prometheus endpoint path
management.endpoints.web.base-path=/actuator

# Health endpoint (optional hardening)
management.endpoint.health.show-details=never


# Enable standard JVM and system metrics
management.prometheus.metrics.export.enabled=true

# Tag all metrics with the application name (Crucial for Dashboard 4701)
management.observations.key-values.application=${spring.application.name}

# (Optional) Record specific histogram buckets for latency graphs
management.metrics.distribution.percentiles-histogram.http.server.requests=true



